### ISSUE TITLE
Using vsphere module

### ISSUE THREAD

**Issue by kratzersmz** [lippserd/docker-compose-icinga#17]
Hi,

i can enable vsphere module, create vsphere db + user. But i cant find the place where i put: /usr/bin/icingacli vspheredb daemon run

icinga2 container doesnt have icingacli installed, any hints on this?

greets

**Comment by t3easy** [comment]
I created a 2nd container with the same image, environment and volumes like the Icinga Web 2 container but with

```yml
command: ["icingacli","vspheredb","daemon","run"]
```

Same for the Director Daemon.

**Comment by lippserd** [comment]
> @lippserd Cool! The x509 plugin also needs a daemon, that can be created like that.

Yeah, I forgot about that one 😆

**Comment by t3easy** [comment]
I also thought about using [Ofelia](https://github.com/mcuadros/ofelia) for some tasks in the stack, but for now, the daemon containers fits my needs.
BTW.: do you have a good idea for icingacli checks? As web and icinga are splitted, the checks can't run as there is no icingacli.

**Comment by lippserd** [comment]
> BTW.: do you have a good idea for icingacli checks? As web and icinga are splitted, the checks can't run as there is no icingacli.

Maybe a Phar of the icingacli plus configuration deployed to the Icinga container. But I don't know if creating the Phar works that easily.

**Comment by t3easy** [comment]
@lippserd maybe we could discuss the possible solutions somewhere else. I extended this stack to my needs with influxdb and grafana and Traefik as reverse proxy. I could contribute back some examples.

**Comment by johnfelipe** [comment]
pls i need help asap

**Comment by t3easy** [comment]
First, you must add an additional MariaDB service to the docker-compose.yml with a dedicated volume for the databases.
e.g.:
```yml
services:
  # ...
  vspheredb-db:
    image: mariadb:${MARIADB_VERSION}
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_bin
    environment:
      MARIADB_DATABASE: vspheredb
      MARIADB_USER: vspheredb
      MARIADB_PASSWORD: ${MARIADB_PASSWORD_VSPHEREDB:?MARIADB_PASSWORD_VSPHEREDB required}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD_VSPHEREDB:?MARIADB_ROOT_PASSWORD_VSPHEREDB required}
      TZ: ${TZ:?TZ required}
    restart: "${RESTART:-always}"
    volumes:
    - vspheredb-db:/var/lib/mysql
  # ...
volumes:
  # ...
  vspheredb-db:
```

You can also add the config to your icingaweb service.
```yml
# ...
environment:
    # ...
    icingaweb.resources.vspheredb-db.charset: utf8mb4
    icingaweb.resources.vspheredb-db.db: mysql
    icingaweb.resources.vspheredb-db.dbname: vspheredb
    icingaweb.resources.vspheredb-db.host: vspheredb-db
    icingaweb.resources.vspheredb-db.password: ${MARIADB_PASSWORD_VSPHEREDB:?MARIADB_PASSWORD_VSPHEREDB required}
    icingaweb.resources.vspheredb-db.type: db
    icingaweb.resources.vspheredb-db.username: vspheredb
    icingaweb.modules.vspheredb.config.db.resource: vspheredb-db
    # ...
```
Then, if necessary, you can cat the sql file from the icingaweb service to the vsphere-db service.

```bash
docker compose exec -T icingaweb2 cat /usr/share/icingaweb2/modules/vspheredb/schema/mysql.sql | docker-compose exec -T vspheredb-db sh -c 'exec mysql -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE"'
```
