### ISSUE TITLE
env ICINGAWEB_MYSQL_PASSWORD is not propagated through configuration

### ISSUE THREAD

**Issue by brianredbeard** [lippserd/docker-compose-icinga#38]
Attempting to deploy while setting `ICINGAWEB_MYSQL_PASSWORD` currently fails due to a bug on line 52 of `docker-compose.yml`:
https://github.com/lippserd/docker-compose-icinga/blob/4bf4395d1959eca2608fdbeefcf616786f26f206/docker-compose.yml#L52

The line should instead set present as:
```yaml
    icingaweb.resources.icingaweb-mysql.password: ${ICINGAWEB_MYSQL_PASSWORD:-icingaweb}
```

**Comment by Tortue95** [comment]
the variable `icingaweb.passwords.icingaweb2.icingaadmin` is not also overloadable by the .env file

in order to correct these 2 problems without modifying the `docker-compose.yml` file I created the docker-`compose.override.yml` file with inside: 

```
services:
  icingaweb:
    environment:
      icingaweb.passwords.icingaweb2.icingaadmin: ${ICINGAWEB_ICINGAADMIN_PASSWORD:-icinga}
      icingaweb.resources.icingaweb-mysql.password: ${ICINGAWEB_MYSQL_PASSWORD:-icingaweb}
```
